baseURL: "https://fuyuki-theme.web.app"
title: "Fuyuki【冬木】"

# !!! SPECIAL ONLY FOR THIS SITE !!!
contentDir: "exampleSite/content/" 

hasCJKLanguage: true

taxonomies:
   tags: "tags"
   categories: "categories"

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: "|"
    lineAnchors: "|"
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: true
    style: nord
    tabWidth: 4

menu:
  main:
    - identifier: home
      name: "Home"
      url: /
      weight: 1
    - identifier: about
      name: "About"
      url: /about/
      weight: 2
  
  social:
    - identifier: github
      name: "Github"
      url: /github/
      weight: 1

params:
  copyright: "©2022 Hoshikawa Shiro"
  description: "A minimalist hugo theme and not lazy designed, i swear!"
  header:
    # Insert icon url (local image/gravatar)
    icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128