baseURL: "https://ichigo-miruku.web.app"
title: "Fuyuki【冬木】"

# !!! SPECIAL ONLY FOR THIS SITE !!!
contentDir: "exampleSite/content/" 

hasCJKLanguage: true

markup:
  tableOfContents:
    startLevel: 1
    ordered: true
    endLevel: 6
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: "|"
    lineAnchors: "|"
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: true
    style: nord
    tabWidth: 4

menu:
  main:
    - identifier: home
      name: "Home"
      url: /
      weight: 1
    
    - identifier: categories
      name: "Categories"
      url: /categories/
      weight: 2
    
    - identifier: about
      name: "About"
      url: /about/
      weight: 3
  
  social:
    - identifier: twitter
      name: "Twitter"
      url: /twitter/
      weight: 1

params:
  useDarkModeToggler: yes
  
  author:
    name: "Hoshikawa Shiro"
    icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
    biot: "yoov"
  
  brand:
    # Insert icon url (local image/gravatar)
    #icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
    # Site description
    description: "A minimalist hugo theme and not lazy designed, i swear!"