baseURL: "https://localhost:1313"
title: "Fuyuki【冬木】"

defaultContentLanguage: id
ignoreErrors: 
  - "error-remote-getjson"

hasCJKLanguage: true
paginate: 16
markup:
  tableOfContents:
    startLevel: 1
    ordered: true
    endLevel: 6
  highlight:
    codeFences: False

menu:
  main:
    - identifier: home
      name: "Home"
      url: /
      weight: 1
    - identifier: pages
      name: pages
      url: /pages/
      weight: 2
    
    - identifier: stats
      name: "Stats"
      url: /stats/
      weight: 3
    
    - identifier: about
      name: "About"
      url: /about/
      weight: 4
  
  social:
    - identifier: twitter
      name: "Twitter"
      url: /twitter/
      weight: 1

markup:
  tableOfContents:
    startLevel: 2
    ordered: false
    endLevel: 5
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  series: series

params:
  useDarkModeToggler: yes
  showTitleOnIndex: yes
  
  hiddenSection:
    - posts
  
  hljs:
    version: 11.5.1
    languages:
      - python
      - go
  
  author:
    name: "Hoshikawa Shiro"
    icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
  brand:
    # Insert icon url (local image/gravatar)
    #icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
    # Site description
    description: "A minimalist hugo theme and not lazy designed, i swear!"
