baseURL: "https://fuyuki.pages.dev"
title: "Fuyuki【冬木】"

defaultContentLanguage: id
ignoreErrors: 
  - "error-remote-getjson"

hasCJKLanguage: true
paginate: 5
markup:
  tableOfContents:
    startLevel: 1
    ordered: true
    endLevel: 6
  highlight:
    codeFences: False

menu:
  main:
    - identifier: home
      name: "Home"
      url: /
      weight: 1
    
    - identifier: about
      name: "About"
      url: /about/
      weight: 2

markup:
  tableOfContents:
    startLevel: 2
    ordered: false
    endLevel: 5
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  series: "series"
  tags: "tags"

params:

  useDarkModeToggler: yes
  showTitleOnIndex: yes
  
  hiddenSection:
    - homepage
  
  hljs:
    version: 11.5.1
    theme: nord
  
  author:
    name: "Hoshikawa Shiro"
    icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
