baseURL: "https://localhost:1313"
title: "Fuyuki【冬木】"

defaultContentLanguage: id
ignoreErrors: 
  - "error-remote-getjson"

hasCJKLanguage: true
paginate: 9
markup:
  tableOfContents:
    startLevel: 1
    ordered: true
    endLevel: 6
  highlight:
    anchorLineNos: true
    codeFences: false
    guessSyntax: true
    hl_Lines: "|"
    lineAnchors: "|"
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    noHl: false
    style: nord
    tabWidth: 4

menu:
  main:
    - identifier: home
      name: "Home"
      url: /
      weight: 1
    - identifier: pages
      name: pages
      url: /pages/
      weight: 2
    
    - identifier: stats
      name: "Stats"
      url: /stats/
      weight: 3
    
    - identifier: about
      name: "About"
      url: /about/
      weight: 4
  
  social:
    - identifier: twitter
      name: "Twitter"
      url: /twitter/
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  useDarkModeToggler: yes
  
  hljs:
    version: 11.5.1
    languages:
      - python
      - go
  
  author:
    name: "Hoshikawa Shiro"
    icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
    biot: "\"Bahkan jika seluruh dunia membenciku, aku akan tetap bisa hidup selama orang itu masih membutuhkanku.\"<b>— Azusagawa Sakuta</b>"
  
  brand:
    # Insert icon url (local image/gravatar)
    #icon: https://s.gravatar.com/avatar/ae7c270bebbeb8c26ba11c27b5296a2f?s=128
    # Site description
    description: "A minimalist hugo theme and not lazy designed, i swear!"
